### ISSUE TITLE
join sample

### ISSUE THREAD

**Issue by abeq** [domaframework/kotlin-sample#1]
Please add 'dept' record to explain how to handle join.

**Comment by nakamura-to** [comment]
See dba8ac16f8a092349ec31f8b937941fa21f80fb1.
Doma just maps a select result to a Java/Kotlin instance.
Association mappings such as one-to-one and one-to-many are not supported.
So you have to write like a `PresonDepartment` class.

**Comment by abeq** [comment]
I got it. Thank you very much.
